services:
  # Next.js application service
  app:
    # Build the Docker image from the current directory
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
    
    # Container name for easy reference
    container_name: eyego-task
    
    # Restart policy: always restart if container stops
    restart: unless-stopped
    
    ports:
      - "3000:3000"
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://localhost:8000}
    
    # Health check to ensure the application is running
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

